### ISSUE TITLE
Initial ICMP support

### ISSUE THREAD

**Issue by abeverley** [frioux/Net-Async-Ping#3]
I've made a start with ICMP support. It _seems_ to work, but a review would be useful.

I'm really not sure about the way that I call $loop->add($socket), but I couldn't get the on_recv code to run otherwise. I then have to remove it from the loop once the data has been received.

https://github.com/abeverley/Net-Async-Ping/blob/master/lib/Net/Async/Ping/ICMP.pm

**Comment by frioux** [comment]
Awesome! I'll look over it this evening after dinner

## 

sent from a rotary phone, pardon my brevity

**Comment by abeverley** [comment]
See #4

**Comment by frioux** [comment]
```$ prove -lr t                                                              9:53:53 am
t/basic.t .. 2/? Can't call method "connect" on an undefined value at /home/frew/code/Net-Async-Ping/lib/Net/Async/Ping/TCP.pm line 76.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with -1 just after 5.
t/basic.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
All 5 subtests passed 

Test Summary Report
-------------------
t/basic.t (Wstat: 65280 Tests: 5 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=5, 11 wallclock secs ( 0.01 usr  0.00 sys +  0.08 cusr  0.01 csys =  0.10 CPU)
Result: FAIL
```

I tried applying this and got the above locally; no idea why :(
